"""Prometheus metrics exported by the AIOps engine on :8000/metrics.
Prometheus scrapes them, Grafana visualises them and alert rules use them."""
from prometheus_client import Counter, Gauge

ANOMALY = Gauge("aiops_anomaly", "1 when the ML ensemble confirms an anomaly")
ANOMALY_SCORE = Gauge("aiops_anomaly_score", "IsolationForest decision score (lower = more anomalous)")
MAX_Z = Gauge("aiops_baseline_max_zscore", "Largest robust z-score vs the learned baseline")
DRIFT = Gauge("aiops_drift_score", "Performance drift of the last minute vs baseline (MAD units)")
CPU_UTIL = Gauge("aiops_cpu_utilization_percent", "App CPU usage as % of its CPU limit")
CPU_PRED = Gauge("aiops_predicted_cpu_utilization_percent", "LSTM forecast of app CPU utilisation")
CAP_FORECAST = Gauge("aiops_capacity_forecast_cpu_percent", "Linear-trend CPU forecast (1 minute ahead)")
FAILURE_RISK = Gauge("aiops_failure_risk", "0 normal, 1 medium, 2 high (LSTM failure prediction)")
HEALTH = Gauge("aiops_health_score", "Infrastructure health score 0-100")
SLA_AVAIL = Gauge("aiops_sla_availability_percent", "Availability over the SLA window")
ERROR_BUDGET = Gauge("aiops_error_budget_remaining_percent", "Remaining error budget over the SLA window")
SLA_COMPLIANT = Gauge("aiops_sla_compliant", "1 when availability and p95 latency meet the SLO")
MEM_MINUTES = Gauge("aiops_memory_minutes_to_exhaustion", "Predicted minutes until app memory limit (-1 = no risk)")
DISK_HOURS = Gauge("aiops_disk_hours_to_full", "Predicted hours until the host disk is full (-1 = no risk)")
INCIDENTS_OPEN = Gauge("aiops_incidents_open", "Open incidents", ["priority"])
INCIDENTS = Counter("aiops_incidents_total", "Incidents opened", ["priority", "rca"])
REMEDIATIONS = Counter("aiops_remediations_total", "Remediation actions", ["action", "result"])
ESCALATIONS = Counter("aiops_escalations_total", "Escalations to a human", ["reason"])
MTTR = Gauge("aiops_mttr_seconds", "Mean time to resolve incidents")
NOISE = Gauge("aiops_alert_noise_reduction_ratio", "1 - incidents / raw signals")
CONFIDENCE = Gauge("aiops_decision_confidence", "Confidence of the latest RCA decision")
CIRCUIT = Gauge("aiops_circuit_breaker_open", "1 when automated remediation is paused by the circuit breaker")
COMPLIANCE_VIOL = Gauge("aiops_compliance_violations", "Failed compliance controls")
COMPLIANCE_SCORE = Gauge("aiops_compliance_score_percent", "Passed compliance controls in %")
SCALE_LEVEL = Gauge("aiops_app_scale_level", "Current vertical scale level of the app (0 = baseline)")
MODEL_TRAINED = Gauge("aiops_model_trained", "1 when the ML models are trained")
TRAINING_RUNS = Gauge("aiops_training_runs", "Number of model training runs (tracked in MLflow)")
