global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    environment: "aiops-demo"
    monitor: "aiops-platform"

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:

  # ---------------- monitoring layer ----------------
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels: {service: "prometheus", layer: "monitoring", region: "cloud"}

  - job_name: "otel"
    static_configs:
      - targets: ["otel-collector:8889"]
        labels: {service: "otel", layer: "observability", region: "cloud"}

  # ---------------- AIOps engine (ML, SLA, remediation metrics) ----------------
  - job_name: "aiops-engine"
    static_configs:
      - targets: ["aiops-engine:8000"]
        labels: {service: "aiops-engine", layer: "aiops", region: "cloud"}

  # ---------------- ON-PREM: business application (Docker) ----------------
  - job_name: "onprem-app"
    metrics_path: /metrics
    scrape_timeout: 3s
    static_configs:
      - targets: ["app:3000"]
        labels: {service: "app", layer: "application", region: "onprem"}

  # ---------------- EDGE: Kubernetes (k3s) ----------------
  - job_name: "kubernetes-edge"
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ["host.docker.internal:30007"]
        labels: {service: "kubernetes-edge", layer: "edge", region: "edge"}

  # ---------------- CLOUD: AWS EC2 host (node-exporter) ----------------
  - job_name: "node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node-exporter:9100"]
        labels: {service: "ec2-host", layer: "infrastructure", region: "cloud", provider: "aws"}

  # ---------------- HYBRID NETWORK MONITORING (blackbox probes) ----------------
  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 15s
    static_configs:
      - targets: ["http://app:3000/health"]
        labels: {layer: "onprem", service: "app"}
      - targets: ["http://host.docker.internal:30007/health"]
        labels: {layer: "edge", service: "kubernetes-edge"}
      - targets: ["http://frontend/"]
        labels: {layer: "frontend", service: "frontend"}
      - targets: ["https://aws.amazon.com"]
        labels: {layer: "internet", service: "network"}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
